### ISSUE TITLE
where is Intentonomy dataset available?　

### ISSUE THREAD

**Issue by kaenkogashi** [KMnP/intentonomy#1]
Thank you for your work!
I want to see the contents of Intentonomy's data set, where is it available?
hope hear from you soon.

**Comment by KMnP** [comment]
Thanks for your interest in Intentonomy. 

We are working on making the data publicly available now. Will update the repo once we release the data.

**Comment by KMnP** [comment]
We just updated repo and included the dataset download information. Let me know if you have any other question.
