### ISSUE TITLE
public dataset

### ISSUE THREAD

**Issue by ericzw** [KMnP/intentonomy#2]
Is there a timeline to public the dataset?

**Comment by KMnP** [comment]
Thanks for your interest. Intentonomy uses a subset of the public Unsplash research dataset (https://unsplash.com/data). We are currently double checking the images and creating mapping from our image id to unsplash id. We plan to release the annotation by the end of this month. 

In the meantime, you can go ahead and download the images from Unsplash first. 

Let me know if you have any other questions!

**Comment by KMnP** [comment]
We just updated repo and included the dataset download information. Let me know if you have any other question.
