### ISSUE TITLE
Some question for annotions

### ISSUE THREAD

**Issue by sidiangongyuan** [KMnP/intentonomy#5]
Why in category_ids_softprob , some probability is more than 1 and some is less than 1.
Are they abandoned datas?

**Comment by KMnP** [comment]
we normalized the annotation by annotators: out of three annotators, if `x`of them think this image belong to one label with id `m`, then this label will have `x/3` in the annotation at position `m`.

**Comment by KMnP** [comment]
the annotators are also annotating one label at a time. You are encouraged to check out our paper for more details about annotation process. 

will close this issue, but feel free to let me know if you have further questions.

**Comment by sidiangongyuan** [comment]
OK I got it. Thank you.
